### ISSUE TITLE
Upload to GitHub

### ISSUE THREAD

**Issue by WestonVincze** [WestonVincze/StolenCreationDemo#4]
I'd like to be able to access and share the project on GitHub

A/C
- Project uploaded to github in the StolenCreationDemo repo
- .gitignore is properly configured

**Comment by Jeffwie** [comment]
I think we should definitely rely on github harder, for both uploads as well as task management,

**Comment by Jeffwie** [comment]
also let me know if you see this, I can't tell if comments are obvious enough
